name: car_app
description: A new Project for Firebase




version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2


  #storage
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_database: ^9.1.0
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.13
  firebase_analytics: ^9.3.0

  #image
  image_picker: ^0.8.5+3
  share_plus: ^4.0.10+1


  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
